version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/urlshortener
      - BASE_URL=http://backend:5000
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_API_BASE_URL: http://backend:5000/api/v1
      REACT_APP_REDIRECT_BASE_URL: http://backend:5000

volumes:
  pgdata:
